name: LK_bulk-env
channels:
  - conda-forge
  - bioconda
  - defaults
  - bioconda/label/cf201901
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.1.5=h516909a_1002
  - atk-1.0=2.36.0=h3371d22_4
  - bamtools=2.5.1=h9a82719_9
  - bcftools=1.17=h3cc50cf_1
  - bedops=2.4.36=h6bb024c_0
  - boost-cpp=1.68.0=h11c811c_1000
  - bowtie2=2.5.4=h7071971_4
  - brotlipy=0.7.0=py27h516909a_1000
  - bx-python=0.8.9=py27h54ae540_2
  - bz2file=0.98=py27_1
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.0=py27he30daa8_1
  - chardet=3.0.4=py27_1003
  - chrpath=0.16=h7f98852_1002
  - colorama=0.4.4=pyhd3eb1b0_0
  - cufflinks=2.2.1=py27_2
  - cutadapt=1.18=py27_0
  - cython=0.29.15=py27haf22ab1_1
  - enum34=1.1.10=py27h8c360ce_1
  - expat=2.5.0=h6a678d5_0
  - fastp=0.24.0=heae3180_1
  - fastqc=0.11.8=1
  - filelock=3.0.12=pyh9f0ad1d_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gatk=3.7=py27_0
  - gatk4=4.3.0.0=py36hdfd78af_0
  - gdbm=1.18=hd4cb3f1_4
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gdown=3.12.2=pyh9f0ad1d_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gffcompare=0.12.6=h4ac6f70_3
  - giflib=5.2.2=hd590300_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.3.0=hac33072_2
  - gnuplot=5.0.3=4
  - graphite2=1.3.14=h295c915_1
  - gsl=2.7=he838d99_0
  - gtk2=2.24.33=h539f30e_1
  - harfbuzz=2.8.1=h6f93f22_0
  - htslib=1.17=h6bc39ce_1
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyhd3eb1b0_0
  - isa-l=2.31.0=h4bc722e_2
  - java-jdk=8.0.92=1
  - jemalloc=5.3.0=h5888daf_1
  - jpeg=9e=h5eee18b_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.12=hddcbb42_0
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libblas=3.9.0=16_linux64_openblas
  - libboost=1.73.0=h28710b8_12
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libffi=3.3=he6710b0_2
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgd=2.3.3=h695aa2c_1
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.68.4=h3e27bee_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjemalloc=5.3.0=h5888daf_1
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libopenblas=0.3.21=h043d6bf_0
  - libopenssl-static=3.0.7=h0b41bf4_1
  - libpng=1.6.43=h2797004_0
  - libpq=9.5.3=1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.2.0=hf544144_3
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h280c20c_1002
  - macs2=2.1.0=0
  - mpfr=4.2.1=h90cbb55_3
  - ncbi-vdb=3.1.1=h4ac6f70_1
  - ncurses=6.4.20240210=h59595ed_0
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - numpy=1.16.5=py27h95a1406_0
  - openjdk=11.0.1=h600c080_1018
  - openssl=1.1.1w=hd590300_0
  - ossuuid=1.6.2=hf484d3e_1000
  - pango=1.48.7=hb8ff022_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.32.1=7_hd590300_perl5
  - perl-alien-build=2.48=pl5321hec16e2b_0
  - perl-alien-libxml2=0.17=pl5321hec16e2b_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321ha770c72_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.022=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-test2-suite=0.000145=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-uri=5.17=pl5321ha770c72_0
  - perl-xml-libxml=2.0207=pl5321h661654b_0
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - picard=2.20.4=0
  - pigz=2.6=h27cfd23_0
  - pip=19.3.1=py27_0
  - piranha=0.11=h522f949_1002
  - pixman=0.43.2=h59595ed_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pysam=0.8.4=py27_0
  - pysocks=1.7.1=py27_0
  - python=2.7.18=ha1903f6_2
  - python-lzo=1.12=py27h42e1302_1001
  - python_abi=2.7=1_cp27mu
  - readline=8.2=h5eee18b_0
  - regtools=1.0.0=hdcf5f25_2
  - requests=2.13.0=py27_0
  - rmats=4.0.2=py27h24bf2e0_0
  - rseqc=2.6.4=py27_0
  - salmon=0.12.0=h86b0361_1
  - scipy=1.2.1=py27h921218d_2
  - sed=4.8=h7b6447c_0
  - seqkit=2.9.0=h9ee0642_0
  - seqtk=1.4=he4a0461_2
  - setuptools=44.0.0=py27_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sra-tools=2.9.6=hf484d3e_0
  - star=2.7.10b=h9ee0642_0
  - stringtie=2.1.7=h978d192_0
  - subread=1.6.3=ha92aebf_0
  - tabix=1.11=hdfd78af_0
  - tbb=2020.3=hfd86e86_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.65.0=pyhd8ed1ab_0
  - trim-galore=0.5.0=0
  - urllib3=1.20=py27_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xopen=0.4.1=py_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
prefix: /tscc/nfs/home/kal084/miniconda3/envs/LK_bulk-env
